services:
  - type: web
    name: stark-backend
    env: docker
    region: ohio
    plan: starter
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: BACKEND_PORT
        value: "8000"
      - key: DATA_PATH
        value: /data
      - key: DEFAULT_WHISPER_MODEL
        value: tiny.en
      - key: CORS_ORIGINS
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
    disk:
      name: stark-data
      mountPath: /data
      sizeGB: 1
